# Generated by Django 4.2.7 on 2024-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("burgerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("task", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
